### ISSUE TITLE
cvise_bug_N directories from cvise-2.1.0 runs

### ISSUE THREAD

**Issue by doko42** [marxin/cvise#48] opened 2021-03-12 08:03 UTC
sending these for some runs from last week:
https://people.debian.org/~doko/tmp/cvise-2.1.0-bugs.tar.xz

**Comment by marxin** [comment] 2021-03-12 09:33
Apparently, all are about a `ClangPass::reduce-pointer-level` issue.
Unfortunately, I cannot reproduce any of these:
```
$ ./clang_delta/clang_delta --transformation=reduce-pointer-level --counter=20 cvise-2.1.0-bugs/cvise_bug_0/foo.ii  >/dev/null
$ echo $?
```

Can you try to reproduce it locally in gdb or valgrind tool?

**Comment by marxin** [comment] 2022-07-08 13:21
Hopefully, it's fixed now.

**Closed by marxin** 2022-07-08 13:21 UTC
